"""Write the synthetic corpus to `tests/corpus/` and print its manifest.

    uv run python -m tests.protocol.generate_corpus

Run deliberately and review the diff, like `generate_golden`: the committed files
are the corpus, `test_synthetic_corpus.py` fails when they drift from what this
would write, and the expectations in `corpus.py` / `test_corpus.py` are typed in
from a reviewed run of the manifest this prints, never regenerated by tooling.
"""

from __future__ import annotations

from tests.protocol.corpus import CORPUS_DIR
from tests.protocol.synthetic import generate, manifest


def main() -> None:
    files = generate()
    CORPUS_DIR.mkdir(exist_ok=True)
    for name, text in files.items():
        path = CORPUS_DIR / name
        existing = path.read_text() if path.is_file() else None
        path.write_text(text)
        verb = "unchanged" if existing == text else "written"
        print(f"{path} {verb}: {text.count(chr(10))} lines")
    print()
    print(manifest(files), end="")


if __name__ == "__main__":
    main()
