"""Corpus replay: the protocol layer verified against the synthetic corpus.

282 frame records in three generated files (`tests/corpus/`, written by
`tests.protocol.synthetic` from a fixed seed): a receive-only ambient mesh, group
text on two channels, and an exchange between sighop and a synthetic peer that
includes a room. What this proves and — just as importantly — what it does not, is
written down in `CORPUS.md`. In short: it proves framing, adverts, signature
verification and that the decoders agree with sighop's own encoders; it does not
prove interoperability with another MeshCore implementation, because the corpus is
generated by the code under test.
"""

from __future__ import annotations

import collections
from pathlib import Path

import pytest

from sighop.protocol.crypto import VerifiedAdvert, verify_advert
from sighop.protocol.packet import Packet, PayloadType, RouteType, decode, encode
from sighop.protocol.payloads import (
    Advert,
    DiscoverRequest,
    DiscoverResponse,
    NodeType,
    build_payload,
    parse_payload,
)
from sighop.protocol.result import DecodeFailure
from tests.protocol.corpus import (
    CORPUS_DIR,
    CORPUS_FILES,
    EXPECTED_FRAME_COUNT,
    CorpusError,
    CorpusFrame,
    load_corpus,
)
from tests.protocol.generate_golden import GOLDEN_PATH
from tests.protocol.golden import render_corpus
from tests.protocol.synthetic import GENERATOR_VERSION, SEED, build_cast

# Recorded expectations, typed in from a reviewed run of the generator's manifest
# (`uv run python -m tests.protocol.generate_corpus`) and asserted, never rewritten
# by tooling (design D10). A change to the generator changes the drift check, the
# manifest and these numbers together, in one reviewed change.
#
# Composition, over all 282 records — 264 received, 18 transmitted by sighop in
# the exchange file. Repeats are counted: 23 receptions repeat a packet already
# seen, all declared in the generator (`test_synthetic_corpus.py`).
EXPECTED_PAYLOAD_TYPES = {
    PayloadType.GRP_TXT: 59,
    PayloadType.TXT_MSG: 43,
    PayloadType.CONTROL: 25,
    PayloadType.ADVERT: 81,
    PayloadType.ACK: 24,
    PayloadType.ANON_REQ: 14,
    PayloadType.PATH: 14,
    PayloadType.RESPONSE: 7,
    PayloadType.REQ: 5,
    PayloadType.GRP_DATA: 4,
    PayloadType.TRACE: 6,
}
EXPECTED_ROUTE_TYPES = {
    RouteType.FLOOD: 188,
    RouteType.DIRECT: 93,
    RouteType.TRANSPORT_FLOOD: 1,
}
EXPECTED_HOP_COUNTS = {0: 83, 1: 73, 2: 57, 3: 43, 4: 19, 5: 7}
EXPECTED_HASH_SIZES = {1: 140, 2: 83, 3: 59}
EXPECTED_ADVERT_COUNT = 81
EXPECTED_ADVERT_FORMS = {0x92: 53, 0x81: 10, 0x91: 9, 0x93: 4, 0x83: 5}
"""By appdata flags: 0x92 repeater (located, named), 0x81 chat (named, no
location), 0x91 chat (located), 0x93 room server (located), 0x83 room server (no
location — the room sighop hosts)."""
EXPECTED_ADVERT_NAMES = 25
# The one transport-routed frame in the corpus: a TRANSPORT_FLOOD advert. Its codes
# are recorded here so a codec change that stops reading them fails on the corpus
# as well as on a hand-built fixture.
EXPECTED_TRANSPORT_FRAMES = 1
EXPECTED_TRANSPORT_CODES = (11329, 0)

# Every CONTROL frame the corpus holds is node discovery (decode-control-discovery),
# by (kind, payload length). The 14-byte key-prefix response is not generated and
# stays a hand-built fixture.
EXPECTED_CONTROL_FORMS = {
    ("discover_request", 6): 2,
    ("discover_request", 10): 3,
    ("discover_response", 38): 20,
}


@pytest.fixture(scope="module")
def frames() -> tuple[CorpusFrame, ...]:
    return load_corpus()


@pytest.fixture(scope="module")
def decoded(frames: tuple[CorpusFrame, ...]) -> list[tuple[CorpusFrame, Packet]]:
    out: list[tuple[CorpusFrame, Packet]] = []
    for frame in frames:
        packet = decode(frame.raw)
        assert isinstance(packet, Packet), f"frame failed to decode: {frame.describe()} -> {packet}"
        out.append((frame, packet))
    return out


# --- Replay ----------------------------------------------------------------


def test_corpus_holds_the_recorded_number_of_frames(
    frames: tuple[CorpusFrame, ...],
) -> None:
    assert len(frames) == EXPECTED_FRAME_COUNT


def test_every_corpus_frame_decodes(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    assert len(decoded) == EXPECTED_FRAME_COUNT


def test_every_corpus_payload_parses(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    for frame, packet in decoded:
        parsed = parse_payload(packet.payload_type, packet.payload)
        assert not isinstance(parsed, DecodeFailure), (
            f"payload failed to parse: {frame.describe()} -> {parsed}"
        )


def test_a_missing_corpus_file_fails_loudly(tmp_path: Path) -> None:
    """Never a silent pass on an empty corpus."""
    from tests.protocol import corpus

    with pytest.raises(CorpusError, match="missing"):
        original = corpus.CORPUS_DIR
        try:
            corpus.CORPUS_DIR = tmp_path
            corpus._load_file(CORPUS_FILES[0])
        finally:
            corpus.CORPUS_DIR = original


def test_corpus_files_are_treated_as_read_only(
    frames: tuple[CorpusFrame, ...],
) -> None:
    """The corpus files are generated artefacts that only the generator writes.
    Recording their digests here makes a stray write by the harness fail.
    """
    import hashlib

    for name in CORPUS_FILES:
        path = CORPUS_DIR / name
        assert path.is_file(), f"corpus file missing: {path}"
        before = hashlib.sha256(path.read_bytes()).hexdigest()
        load_corpus()
        after = hashlib.sha256(path.read_bytes()).hexdigest()
        assert before == after, f"the harness modified {name}"


def test_every_corpus_file_carries_synthetic_provenance(
    frames: tuple[CorpusFrame, ...],
) -> None:
    """A file with no `capture_meta` header is of unrecorded origin: neither
    generated nor evidence. Every corpus file is generated, and says so, with the
    generator version and seed that wrote it — and there is no sidecar.
    """
    import json

    for name in CORPUS_FILES:
        path = CORPUS_DIR / name
        with path.open("r", encoding="utf-8") as handle:
            first = json.loads(handle.readline())
        assert first.get("kind") == "capture_meta", f"{name} has no capture_meta header"
        assert first.get("synthetic") is True, f"{name} does not say it is synthetic"
        assert first["generator"]["version"] == GENERATOR_VERSION, name
        assert first["generator"]["seed"] == SEED, name
        assert not path.with_suffix(".meta.json").exists(), f"{name} has a sidecar"
    assert sorted(p.name for p in CORPUS_DIR.iterdir()) == sorted(CORPUS_FILES), (
        "the corpus directory holds a file the harness does not name"
    )


# --- Round-trip ------------------------------------------------------------


def test_every_corpus_frame_re_encodes_byte_identically(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    for frame, packet in decoded:
        assert encode(packet) == frame.raw, f"re-encode differs: {frame.describe()}"


def test_every_corpus_payload_rebuilds_byte_identically(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    for frame, packet in decoded:
        parsed = parse_payload(packet.payload_type, packet.payload)
        assert not isinstance(parsed, DecodeFailure)
        assert build_payload(parsed) == packet.payload, (
            f"payload rebuild differs: {frame.describe()}"
        )


# --- Distributions ---------------------------------------------------------


def test_payload_type_distribution_holds(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    counts = collections.Counter(packet.payload_type for _, packet in decoded)
    assert dict(counts) == EXPECTED_PAYLOAD_TYPES


def test_route_type_distribution_holds(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    counts = collections.Counter(packet.route_type for _, packet in decoded)
    assert dict(counts) == EXPECTED_ROUTE_TYPES


def test_hop_count_distribution_holds(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    counts = collections.Counter(packet.hop_count for _, packet in decoded)
    assert dict(counts) == EXPECTED_HOP_COUNTS


def test_path_hash_size_distribution_holds(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    """All three live path hash sizes are present, so a reader that assumes
    1-byte hashes (DESIGN.md §4.2's original `path_length > 64` rule) is caught
    by the corpus and not only by a hand-built frame.
    """
    counts = collections.Counter(packet.hash_size for _, packet in decoded)
    assert dict(counts) == EXPECTED_HASH_SIZES


def test_the_one_transport_routed_frame_decodes_with_its_codes(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    """One frame, so this asserts it exactly rather than a distribution: a codec
    change that drops the transport-code field, or reads it as path bytes, fails
    here on the corpus as well as on `test_packet.py`'s hand-built fixture, which
    stays. `TRANSPORT_DIRECT` is not generated and is covered only by that fixture.
    """
    routed = [(frame, packet) for frame, packet in decoded if packet.transport_codes is not None]

    assert len(routed) == EXPECTED_TRANSPORT_FRAMES
    frame, packet = routed[0]
    assert packet.route_type is RouteType.TRANSPORT_FLOOD, frame.describe()
    assert packet.transport_codes == EXPECTED_TRANSPORT_CODES, frame.describe()
    assert packet.payload_type is PayloadType.ADVERT, frame.describe()


def test_every_corpus_control_frame_decodes_as_discovery(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> None:
    """Every corpus CONTROL frame is a discovery request or response, and none
    falls back to uninterpreted. The byte-identical rebuild is
    `test_every_corpus_payload_rebuilds_byte_identically`'s."""
    forms: collections.Counter[tuple[str, int]] = collections.Counter()
    for frame, packet in decoded:
        if packet.payload_type is not PayloadType.CONTROL:
            continue
        parsed = parse_payload(packet.payload_type, packet.payload)
        match parsed:
            case DiscoverRequest():
                forms["discover_request", len(packet.payload)] += 1
            case DiscoverResponse():
                assert parsed.node_type_name is NodeType.REPEATER, frame.describe()
                forms["discover_response", len(packet.payload)] += 1
            case _:
                pytest.fail(f"CONTROL frame did not decode as discovery: {frame.describe()}")

    assert dict(forms) == EXPECTED_CONTROL_FORMS


# --- Adverts ---------------------------------------------------------------


@pytest.fixture(scope="module")
def adverts(
    decoded: list[tuple[CorpusFrame, Packet]],
) -> list[tuple[CorpusFrame, Advert]]:
    out: list[tuple[CorpusFrame, Advert]] = []
    for frame, packet in decoded:
        if packet.payload_type is not PayloadType.ADVERT:
            continue
        parsed = parse_payload(packet.payload_type, packet.payload)
        assert isinstance(parsed, Advert)
        out.append((frame, parsed))
    return out


def test_all_corpus_adverts_verify(
    adverts: list[tuple[CorpusFrame, Advert]],
) -> None:
    assert len(adverts) == EXPECTED_ADVERT_COUNT
    for frame, advert in adverts:
        result = verify_advert(advert)
        assert isinstance(result, VerifiedAdvert), (
            f"advert failed verification: {frame.describe()} -> {result}"
        )


def test_tampering_with_a_corpus_advert_breaks_verification(
    adverts: list[tuple[CorpusFrame, Advert]],
) -> None:
    _, advert = adverts[0]
    tampered = Advert(
        public_key=advert.public_key,
        timestamp=advert.timestamp ^ 1,
        signature=advert.signature,
        appdata=advert.appdata,
    )
    assert not isinstance(verify_advert(tampered), VerifiedAdvert)


def test_corpus_advert_names_and_types_decode_consistently(
    adverts: list[tuple[CorpusFrame, Advert]],
) -> None:
    """Names decode cleanly only under the multi-byte path hash encoding: read
    with 1-byte hashes, the corpus's multi-hop adverts yield truncated names and
    corrupt flags (`test_synthetic_corpus.py` asserts that reading directly).
    """
    cast = build_cast()
    named = 0
    names: set[str] = set()
    forms: collections.Counter[int] = collections.Counter()
    for frame, advert in adverts:
        result = verify_advert(advert)
        assert isinstance(result, VerifiedAdvert)
        assert isinstance(result.appdata.node_type, NodeType), (
            f"unknown node type in {frame.describe()}"
        )
        forms[result.appdata.flags] += 1
        if result.appdata.name is not None:
            assert result.appdata.name.is_valid_utf8, (
                f"advert name is not valid UTF-8: {frame.describe()}"
            )
            names.add(result.appdata.name.text)
            named += 1
    assert named == EXPECTED_ADVERT_COUNT, "every corpus advert carries a name"
    assert dict(forms) == EXPECTED_ADVERT_FORMS
    assert len(names) == EXPECTED_ADVERT_NAMES
    assert names == set(cast.names), (
        "every advertised name is the cast's, and every cast node advertises"
    )


# --- Golden file -----------------------------------------------------------


def test_decoded_output_matches_the_golden_file() -> None:
    assert GOLDEN_PATH.is_file(), (
        f"{GOLDEN_PATH} is missing; regenerate it with "
        "`uv run python -m tests.protocol.generate_golden` and review the diff"
    )
    assert render_corpus() == GOLDEN_PATH.read_text()


def test_golden_file_contains_no_decrypted_content() -> None:
    """Design D8: structural fields and ciphertext digests only. The generator
    holds every key in the synthetic corpus, so plaintext could be rendered here
    and is not: the rule is asserted so it also holds if a recorded frame is ever
    added.
    """
    data_lines = [line for line in GOLDEN_PATH.read_text().splitlines() if not line.startswith("#")]
    assert data_lines
    for line in data_lines:
        assert "plaintext" not in line
        assert "decrypted" not in line
        if " len=" in line:
            # Every rendered ciphertext is reduced to a length and a digest.
            assert " sha=" in line, (
                f"a ciphertext was rendered without being reduced to a digest: {line}"
            )
