"""MeshCore protocol layer: pure functions over bytes.

Per DESIGN.md §11 this layer depends on nothing else in sighop — no radio, no
database, no network, no event loop — which `tests/protocol/test_import_boundary.py`
enforces against the source.

The decode path runs in three stages with different trust levels (design D2):

    packet.decode(raw)                  -> Packet | DecodeFailure
    payloads.parse_payload(type, bytes) -> envelope | DecodeFailure
    crypto.mac_then_decrypt(...)        -> body bytes, only with the right key

Decoding returns failures rather than raising (design D3); encoding raises
`EncodeError`, because its inputs are ours.
"""

from sighop.protocol.crypto import (
    PUBLIC_CHANNEL_KEY,
    AdvertVerificationFailure,
    ChannelKey,
    MacCandidateMatch,
    SharedSecretCache,
    VerifiedAdvert,
    ack_checksum,
    ack_checksum_for,
    calc_shared_secret,
    channel_key_from_hashtag,
    compute_mac,
    decrypt,
    encrypt,
    encrypt_then_mac,
    mac_then_decrypt,
    shared_secret_from_scalar,
    sign_advert,
    verify_advert,
    verify_mac,
)
from sighop.protocol.identity import (
    Identity,
    IdentityGenerationError,
    LocalIdentity,
    generate_identity,
)
from sighop.protocol.packet import (
    MAX_PACKET_PAYLOAD,
    MAX_PATH_SIZE,
    MAX_TRANS_UNIT,
    Packet,
    PacketHeader,
    PayloadType,
    RouteType,
)
from sighop.protocol.packet import decode as decode_packet
from sighop.protocol.packet import encode as encode_packet
from sighop.protocol.payloads import (
    Acknowledgement,
    Advert,
    AdvertAppData,
    AnonRequestEnvelope,
    ClientKind,
    DirectEnvelope,
    DiscoverRequest,
    DiscoverResponse,
    GroupEnvelope,
    GroupTextBody,
    LppType,
    NodeType,
    ParsedPayload,
    Permission,
    RequestBody,
    RequestType,
    ReturnedPathBody,
    RoomLoginBody,
    RoomLoginResponseBody,
    ServerStats,
    StatusBody,
    TelemetryEntry,
    TextMessageBody,
    TextType,
    TracePayload,
    UnparsedPayload,
    WireText,
    build_discover_request,
    build_discover_response,
    build_group_text_body,
    build_payload,
    build_request_body,
    build_returned_path_body,
    build_room_login_body,
    build_room_login_response_body,
    build_status_body,
    build_telemetry_frame,
    build_text_message_body,
    parse_appdata,
    parse_control,
    parse_group_text_body,
    parse_payload,
    parse_request_body,
    parse_returned_path_body,
    parse_room_login_body,
    parse_room_login_response_body,
    parse_status_body,
    parse_telemetry_frame,
    parse_text_message_body,
    temperature_entry,
    voltage_entry,
)
from sighop.protocol.result import (
    DecodeFailure,
    DecodeResult,
    EncodeError,
    FailureReason,
)

__all__ = [
    "MAX_PACKET_PAYLOAD",
    "MAX_PATH_SIZE",
    "MAX_TRANS_UNIT",
    "PUBLIC_CHANNEL_KEY",
    "Acknowledgement",
    "Advert",
    "AdvertAppData",
    "AdvertVerificationFailure",
    "AnonRequestEnvelope",
    "ChannelKey",
    "ClientKind",
    "DecodeFailure",
    "DecodeResult",
    "DirectEnvelope",
    "DiscoverRequest",
    "DiscoverResponse",
    "EncodeError",
    "FailureReason",
    "GroupEnvelope",
    "GroupTextBody",
    "Identity",
    "IdentityGenerationError",
    "LocalIdentity",
    "LppType",
    "MacCandidateMatch",
    "NodeType",
    "Packet",
    "PacketHeader",
    "ParsedPayload",
    "PayloadType",
    "Permission",
    "RequestBody",
    "RequestType",
    "ReturnedPathBody",
    "RoomLoginBody",
    "RoomLoginResponseBody",
    "RouteType",
    "ServerStats",
    "SharedSecretCache",
    "StatusBody",
    "TelemetryEntry",
    "TextMessageBody",
    "TextType",
    "TracePayload",
    "UnparsedPayload",
    "VerifiedAdvert",
    "WireText",
    "ack_checksum",
    "ack_checksum_for",
    "build_discover_request",
    "build_discover_response",
    "build_group_text_body",
    "build_payload",
    "build_request_body",
    "build_returned_path_body",
    "build_room_login_body",
    "build_room_login_response_body",
    "build_status_body",
    "build_telemetry_frame",
    "build_text_message_body",
    "calc_shared_secret",
    "channel_key_from_hashtag",
    "compute_mac",
    "decode_packet",
    "decrypt",
    "encode_packet",
    "encrypt",
    "encrypt_then_mac",
    "generate_identity",
    "mac_then_decrypt",
    "parse_appdata",
    "parse_control",
    "parse_group_text_body",
    "parse_payload",
    "parse_request_body",
    "parse_returned_path_body",
    "parse_room_login_body",
    "parse_room_login_response_body",
    "parse_status_body",
    "parse_telemetry_frame",
    "parse_text_message_body",
    "shared_secret_from_scalar",
    "sign_advert",
    "temperature_entry",
    "verify_advert",
    "verify_mac",
    "voltage_entry",
]
